language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-32.0.0
    - android-32
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew

script:
  # Build the project
  - ./gradlew build

  # Run unit tests
  - ./gradlew test

  # Run UI tests
  - ./gradlew connectedAndroidTest

notifications:
  email: false